# This file was *autogenerated* from the file correspondencia.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_1 = Integer(1); _sage_const_6 = Integer(6)
def corresp (p, a, b):
	f = GF(p)
	alpha = f.primitive_element
	print "for p = " + str(p) + " and (a, b) = (" + str(a) + ", " + str(b) + "): "
	for k in range(_sage_const_1 , _sage_const_6 ):
	    for i in range(_sage_const_1 , int((p-_sage_const_1 )/_sage_const_6 )):
	    	res = (alpha**((_sage_const_6 *k)+i)) * (((-_sage_const_1 )**i) + a*((alpha**(i * int((p-_sage_const_1 )/_sage_const_6 )))) + b)%p
	        print ("k: " + str(k) + ", i: " + str(i) + " = " + str(res))
	print "for p = " + str(p) + " and (a, b) = (" + str(a) + ", " + str(b) + "): "
	for k in range(_sage_const_1 , _sage_const_6 ):
		for i in range(_sage_const_1 , int((p-_sage_const_1 )/_sage_const_6 )):
			res = (alpha**((_sage_const_6 *k)+i)) * (((-_sage_const_1 )**i) + a*((alpha**(i * int((p-_sage_const_1 )/_sage_const_6 )))) + (-b))%p
			print ("k: " + str(k) + ", i: " + str(i) + " = " + str(res))

