# This file was *autogenerated* from the file examples.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_31 = Integer(31); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5)# Compute examples of case 6k = case 6l+1

k = GF(_sage_const_31 )
A = k.primitive_element()

for m in range(_sage_const_1 ,_sage_const_6 ):
	for a in k:
		for b in k:
			check = A**(_sage_const_6 *m)
			if k(_sage_const_1 +b+a) != _sage_const_0 :
				if A*k((_sage_const_1 +a*A**(_sage_const_5 )+b)/k(_sage_const_1 +a+b))==check:
					print m,a,b
